// Título: Calcular desconto

// O que fazer no desafio:
// Crie uma Arrow Function que receba:
// valorProduto e desconto
//
// Exemplo:
// produto = 100
// desconto = 20
//
// Resultado esperado:
// 80

// Resultado:
let valorProduto = 100
let desconto = 20
const calcularDesconto = 






// Título: Contar letras

// O que fazer no desafio:
// Crie uma Arrow Function que receba uma palavra
// e retorne quantas letras ela possui.

// Resultado:
//const contarLetras =






// Título: Verificar número par

// O que fazer no desafio:
// Crie uma Arrow Function que receba um número
// e retorne:
//
// "Par"
// ou
// "Ímpar"

// Resultado:
//const verificarParidade =







// Título: Encontrar o maior número

// O que fazer no desafio:
// Crie uma Arrow Function que receba
// dois números e retorne o maior deles.

// Resultado:
//const maiorNumero =







// Título: Calcular área do retângulo

// O que fazer no desafio:
// Crie uma Arrow Function que receba
// largura e altura.
//
// Retorne a área do retângulo.

// Resultado:
//const calcularArea =