// Título: Somar números de um array

// O que fazer no desafio:
// Crie uma Arrow Function que receba um array
// de números e retorne a soma total.
//
// Exemplo:
// [10,20,30]
//
// Resultado esperado:
// 60

// Resultado:
let numeroArray = [19,29,48]
const somarArray = (numeroArray) => {
    for(let i =0; i < numeroArray.length; i++){
        let numeroAtual = 0
        i + numeroAtual
    }
}
console.log(somarArray(numeroArray))

 






// Título: Encontrar maior valor do array

// O que fazer no desafio:
// Crie uma Arrow Function que receba um array
// de números e retorne o maior valor.
//
// Exemplo:
// [5,8,2,20,1]
//
// Resultado esperado:
// 20

// Resultado:
//const maiorValor =









// Título: Contar vogais

// O que fazer no desafio:
// Crie uma Arrow Function que receba uma string
// e retorne a quantidade de vogais. 
//
// Exemplo:
// "javascript"
//
// Resultado esperado:
// 3

// Resultado:
//const contarVogais =










// Título: Filtrar números pares

// O que fazer no desafio:
// Crie uma Arrow Function que receba um array
// e retorne apenas os números pares.
//
// Exemplo:
// [1,2,3,4,5,6]
//
// Resultado esperado:
// [2,4,6]

// Resultado:
//const filtrarPares =









// Título: Gerar relatório de aprovação

// O que fazer no desafio:
// Crie uma Arrow Function que receba uma nota.
//
// Se a nota for maior ou igual a 7:
// "Aprovado"
//
// Caso contrário:
// "Reprovado"

// Resultado:
//const verificarAprovacao =